<?php
session_start();

// 1. Enable error reporting for debugging (Remove in production if preferred)
error_reporting(E_ALL);
ini_set('display_errors', 1);

// 2. Load the existing logic to get filters and summary stats
//    We use output buffering to capture any unwanted whitespace or includes
ob_start(); 
require_once __DIR__ . '/staff_dashboard-action.php';
ob_end_clean(); // Discard any HTML output from the action file

// 3. Fetch the FULL LIST of appointments based on the current filter
$sql_full_list = "SELECT a.appointment_id, a.full_name, ser.service_name, 
                         a.appointment_date, a.appointment_time, s.status_name,
                         a.phone_number, a.gender, a.age
                  FROM appointments a
                  LEFT JOIN services ser ON a.service_id = ser.service_id
                  LEFT JOIN appointmentstatus s ON a.status_id = s.status_id
                  WHERE {$statFilter} 
                  ORDER BY a.appointment_date ASC, a.appointment_time ASC";
$result_full = $conn->query($sql_full_list);

// 4. Set Headers to force download as CSV (Excel compatible)
$filename = "EyeMaster_Dashboard_Report_" . date('Y-m-d_His') . ".csv";
header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Pragma: no-cache');
header('Expires: 0');

// 5. Open PHP Output Stream
$output = fopen('php://output', 'w');

// --- HELPER: Write a line to CSV ---
function writeLine($handle, $array) {
    fputcsv($handle, $array);
}

// --- SECTION 1: REPORT HEADER ---
writeLine($output, ['EYE MASTER CLINIC - MANAGEMENT DASHBOARD REPORT']);
writeLine($output, []); // Empty Row
writeLine($output, ['Generated By:', $_SESSION['full_name'] ?? 'Admin']);
writeLine($output, ['Date Generated:', date('F j, Y, g:i a')]);
writeLine($output, ['Filter Applied:', "Year: $filterYear | Month: $filterMonth | Week: $filterWeek | Day: $filterDay"]);
writeLine($output, []); 
writeLine($output, []); 

// --- SECTION 2: COMPUTATION SUMMARY (The Cards) ---
writeLine($output, ['--- EXECUTIVE SUMMARY STATISTICS ---']);
writeLine($output, ['Metric', 'Count', 'Description']);
writeLine($output, ['Total Appointments', $totalAppointmentsToday, 'All appointments within selected range']);
writeLine($output, ['Confirmed Appointments', $confirmedAppointments, 'Appointments confirmed and scheduled']);
writeLine($output, ['Pending Appointments', $pendingAppointments, 'Appointments awaiting approval']);
writeLine($output, ['Completed Appointments', $completedToday, 'Successfully finished appointments']);
// REMOVED MISSED APPOINTMENTS ROW HERE
writeLine($output, []); 
writeLine($output, []); 

// --- SECTION 3: APPOINTMENT STATUS BREAKDOWN ---
writeLine($output, ['--- STATUS DISTRIBUTION BREAKDOWN ---']);
writeLine($output, ['Status Name', 'Count']);
foreach ($statusData as $row) {
    writeLine($output, [$row['status_name'], $row['count']]);
}
writeLine($output, []); 
writeLine($output, []); 

// --- SECTION 4: DETAILED APPOINTMENT LIST ---
writeLine($output, ['--- DETAILED APPOINTMENT LOG (FILTERED) ---']);
writeLine($output, [
    'Appt ID', 
    'Patient Name', 
    'Service', 
    'Date', 
    'Time', 
    'Status', 
    'Phone', 
    'Gender',
    'Age'
]);

if ($result_full && $result_full->num_rows > 0) {
    while ($row = $result_full->fetch_assoc()) {
        // Decrypt name if needed
        $fullName = function_exists('decrypt_data') ? decrypt_data($row['full_name']) : $row['full_name'];
        
        // FIX: Add a tab character "\t" before numbers to force Excel to treat them as text
        // This stops it from formatting dates incorrectly or hiding phone numbers
        $formattedDate = "\t" . $row['appointment_date']; 
        $formattedPhone = "\t" . $row['phone_number'];
        
        writeLine($output, [
            $row['appointment_id'],
            $fullName,
            $row['service_name'],
            $formattedDate,  // Fixed Date
            date('g:i A', strtotime($row['appointment_time'])),
            $row['status_name'],
            $formattedPhone, // Fixed Phone Number
            $row['gender'],
            $row['age']
        ]);
    }
} else {
    writeLine($output, ['No records found for this specific date/filter.']);
}

// Close stream
fclose($output);
exit;
?>