<?php
session_start();
require_once __DIR__ . '/staff_dashboard-action.php';
require_once __DIR__ . '/../../config/encryption_util.php';
?>

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eye Master Clinic - Admin Dashboard</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://unpkg.com/html5-qrcode"></script>
<link rel="stylesheet" href="staff_dashboard.css?v=<?php echo @filemtime(__DIR__ . '/staff_dashboard.css') ?: time(); ?>">
<style>
/* =========================================
   PRINT SPECIFIC STYLES (Professional Report)
   ========================================= */
@media print {
    /* 1. Hide Non-Print Elements */
    header, #menu-toggle, .filter-group, .qr-section, .bottom-section .scan-btn, 
    footer, .toast-overlay, .popup-overlay, #loader-overlay, 
    .welcome-section .welcome-text, .detail-overlay, .qr-modal-overlay, .filter-btn {
        display: none !important;
    }

    /* 2. Reset Layout for Paper */
    body {
        background-color: white !important;
        color: black !important;
        font-family: 'Times New Roman', Times, serif; /* Professional font for reports */
        font-size: 12pt;
    }

    .dashboard {
        padding: 0;
        margin: 0;
        width: 100%;
        max-width: 100%;
        background: white !important;
        box-shadow: none !important;
    }

    /* 3. Show Print Header */
    .print-header {
        display: block !important;
        text-align: center;
        margin-bottom: 20px;
        border-bottom: 2px solid #000;
        padding-bottom: 15px;
    }
    .print-header h1 { margin: 0; font-size: 24px; color: #000; text-transform: uppercase; }
    .print-header p { margin: 5px 0 0; font-size: 14px; color: #333; }

    /* 4. Format Statistics Cards (Grid to Table-like look) */
    .stats {
        display: grid !important;
        grid-template-columns: 1fr 1fr !important;
        gap: 15px;
        margin-bottom: 30px;
    }

    .stats .card {
        border: 1px solid #000 !important;
        background: #fff !important;
        box-shadow: none !important;
        color: #000 !important;
        padding: 15px;
        break-inside: avoid; /* Prevent splitting across pages */
    }

    .stats .card p { color: #000 !important; font-weight: bold; font-size: 14px; }
    .stats .card h2 { color: #000 !important; font-size: 28px; margin-top: 5px; }

    /* 5. Charts (Ensure they fit) */
    .charts-grid {
        display: block !important;
        margin-top: 20px;
    }
    .chart-box {
        border: 1px solid #ddd;
        page-break-inside: avoid;
        margin-bottom: 30px;
        box-shadow: none !important;
        background: #fff !important;
    }

    /* 6. Recent Appointments List (Make it look like a table) */
    .bottom-section {
        display: block !important;
        margin-top: 20px;
    }
    .right-section, .weekly-box {
        width: 100% !important;
        box-shadow: none !important;
        border: 1px solid #ddd;
        margin-bottom: 20px;
    }
    .recent-item {
        border-bottom: 1px solid #ccc;
        color: #000 !important;
    }
    .recent-item h4, .recent-item p { color: #000 !important; }
}

/* Hide print header on normal screen */
.print-header { display: none; }

/* FIX CARDS STRETCHING (From Previous Request) */
.bottom-section {
    align-items: start; 
}
.right-section {
    align-items: start;
}
.qr-section {
    height: fit-content;
    min-height: 250px;
}
</style>
</head>
<body>

<div id="loader-overlay">
    <div class="loader-content">
        <div class="loader-spinner"></div>
        <p id="loader-text">Loading...</p>
    </div>
</div>

<div id="toast-overlay-global" class="toast-overlay" style="z-index: 10000;"></div>

<div class="popup-overlay" onclick="closePopup()"></div>

<header>
    <div class="logo-section">
        <img src="../photo/LOGO.jpg" alt="Logo"> <strong>EYE MASTER CLINIC</strong>
    </div>
    <button id="menu-toggle" aria-label="Open navigation">☰</button>
    <nav id="main-nav">
        <a href="staff_dashboard.php" class="active">🏠 Dashboard</a>
        <a href="appointment.php">📅 Appointments</a>
        <a href="patient_record.php">📘 Patient Record</a>
        <a href="product.php">💊 Product & Services</a>
        <a href="account.php">👤 Account</a>
        <a href="profile.php">🔍 Profile</a>
    </nav>
</header>

<div class="dashboard">

    <div class="print-header">
        <h1>EYE MASTER CLINIC - MANAGEMENT REPORT</h1>
        <p><strong>Generated By:</strong> <?php echo htmlspecialchars($_SESSION['full_name'] ?? 'Admin'); ?></p>
        <p><strong>Date of Report:</strong> <?php echo date('F j, Y, g:i A'); ?></p>
        <p style="margin-top: 5px; font-style: italic;">
            <strong>Filter Applied:</strong> 
            Year: <?= $filterYear ?> | Month: <?= $filterMonth ?> | Week: <?= $filterWeek ?> | Day: <?= $filterDay ?>
        </p>
    </div>

    <div class="welcome-section">
        <div class="welcome-text">
            <h1>Welcome back, <?php echo htmlspecialchars($_SESSION['full_name'] ?? 'Admin'); ?></h1>
            <p>Here's what's happening at your clinic.</p>
        </div>
        <div class="top-controls">
            
            <div class="filter-group">
                <div style="position: relative;">
                    <button class="filter-btn" id="yearBtn" onclick="toggleDropdown('yearDropdown')"><?= $filterYear ?></button>
                    <div id="yearDropdown" class="dropdown">
                        <?= $yearDropdownItems ?>
                    </div>
                </div>

                <div style="position: relative;">
                    <button class="filter-btn" id="monthBtn" onclick="toggleDropdown('monthDropdown')"><?= $filterMonth ?></button>
                    <div id="monthDropdown" class="dropdown">
                        <?= $monthDropdownItems ?>
                    </div>
                </div>

                <div style="position: relative;">
                    <button class="filter-btn" id="weekBtn" onclick="toggleDropdown('weekDropdown')"><?= $weekBtnText ?></button>
                    <div id="weekDropdown" class="dropdown">
                        <?= $weekDropdownItems ?>
                    </div>
                </div>
                
                <div style="position: relative;">
                    <button class="filter-btn" id="dayBtn" onclick="toggleDropdown('dayDropdown')"><?= $dayBtnText ?></button>
                    <div id="dayDropdown" class="dropdown">
                        <?= $dayDropdownItems ?>
                    </div>
                </div>

                <button class="filter-btn" onclick="window.print()" style="background-color: #34495e; color: white;" title="Print Report">
                    🖨️ Print
                </button>

                <a href="staff_dashboard_export.php?<?php echo $_SERVER['QUERY_STRING']; ?>" 
                   class="filter-btn" 
                   style="background-color: #27ae60; color: white; text-decoration: none; display: inline-flex; align-items: center; justify-content: center;" 
                   title="Download Excel Report">
                    📥 Export Excel
                </a>
            </div>
        </div>
    </div>

    <div class="stats">
        <div class="card">
            <p>Total Appointments</p>
            <h2><?= $totalAppointmentsToday ?></h2>
        </div>
        
        <div class="card">
            <p>Pending Appointments</p>
            <h2><?= $pendingAppointments ?></h2>
        </div>

        <div class="card">
            <p>Confirmed Appointments</p>
            <h2><?= $confirmedAppointments ?></h2>
        </div>

        <div class="card">
            <p>Completed Appointments</p>
            <h2><?= $completedToday ?></h2>
        </div>
    </div>

    <div class="charts-grid">
        <div class="chart-box">
            <h3>Appointments Overview</h3>
            <div class="chart-wrapper">
                <canvas id="appointmentsChart"></canvas>
            </div>
        </div>
        
        <div class="chart-box">
            <h3>Appointment Status</h3>
            <div class="chart-wrapper">
                <canvas id="statusChart"></canvas>
            </div>
        </div>
    </div>

    <div class="bottom-section">
        <div class="weekly-box">
            <h3>Weekly Appointments Overview</h3>
            <div class="weekly-wrapper">
                <canvas id="weeklyChart"></canvas>
            </div>
        </div>
        
        <div class="right-section">
            <div class="recent">
                <h3>Recent Appointments</h3>
                <?php if (empty($recentAppointments)): ?>
                    <div class="empty-state">No recent appointments for this filter.</div>
                <?php else: ?>
                    <?php foreach ($recentAppointments as $apt): ?>
                    <div class="recent-item">
                        <div class="recent-item-info">
                            <h4>    <?= htmlspecialchars(decrypt_data($apt['full_name'])) ?></h4>
                            <p><?= htmlspecialchars($apt['service_name']) ?> - <?= date('g:i A', strtotime($apt['appointment_time'])) ?></p>
                        </div>
                        <span class="status <?= strtolower($apt['status_name']) ?>">
                            <?= htmlspecialchars($apt['status_name']) ?>
                        </span>
                    </div>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
            
            <div class="qr-section">
                <div class="qr-code-display">
    <?php 
        // 1. Find the latest CONFIRMED appointment to show as a test
        $qrTestSql = "SELECT appointment_id FROM appointments 
                      JOIN appointmentstatus s ON appointments.status_id = s.status_id 
                      WHERE s.status_name = 'Confirmed' 
                      ORDER BY appointment_date DESC, appointment_time DESC 
                      LIMIT 1";
        $qrTestResult = $conn->query($qrTestSql);
        
        $qrData = "123"; 
        
        if ($qrTestResult && $qrTestResult->num_rows > 0) {
            $qrData = $qrTestResult->fetch_assoc()['appointment_id'];
        }
    ?>
    <img src="https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=<?= $qrData ?>" alt="QR Code for Appt #<?= $qrData ?>">
    <p style="font-size:12px; color:#666; margin-top:5px;">Scan to test (ID: <?= $qrData ?>)</p>
</div>
                <button class="scan-btn" onclick="startScan()">Click to Scan</button>
            </div>
        </div>
    </div>
</div>

<div id="popup">
    <div id="popup-header"><h3>Confirmation</h3></div>
    <div id="popup-content"></div>
    <div id="popup-actions" style="display: flex; justify-content: flex-end; gap: 10px;">
        <button id="confirmActionBtn" style="display: none; background: #27ae60;">Confirm</button>
        <button onclick="closePopup()">Close</button>
    </div>
</div>

<div class="detail-overlay" id="appointmentDetailModal">
    <div class="detail-card">
        
        <div class="detail-header">
            <div class="detail-title" id="detail-title">
                Appointment Details
            </div>
            <span class="detail-id" id="detail-id">#0</span>
        </div>

        <div id="detailModalBody" style="padding: 24px 28px; max-height: 70vh; overflow-y: auto; font-size: 15px;">
            </div>

        <div class="detail-actions">
            <input type="hidden" id="modal_appointment_id" value="">
            <button class="btn-small btn-close" onclick="closeAppointmentDetailModal()">Back</button>
            
            <button class="btn-small btn-cancel" style="background: #dc2626; color: white;" 
                    onclick="promptScannedCancel()">
                Cancel
            </button>
            
            <button class="btn-small btn-accept" style="background: #16a34a; color: white;" 
                    onclick="updateScannedStatus('Completed')">
                Complete
            </button>
        </div>

    </div>
</div>

<div class="qr-modal-overlay" id="qrScannerModal" style="display: none;">
    <div class="qr-modal-content">
        <button class="qr-modal-close" onclick="stopScan()">✕</button>
        <h3>Scan Appointment QR Code</h3>
        <p>Hold the QR code steady in the center of the frame.</p>
        <div id="qr-reader-container">
            <div id="qr-reader"></div>
        </div>
    </div>
</div>

<div id="reasonModal" class="confirm-modal" aria-hidden="true" style="z-index: 3001;">
    <div class="confirm-card" role="dialog" aria-modal="true">
        <div class="confirm-header">
            <div class="confirm-icon danger">!</div>
            <div class="confirm-title">Reason for Cancellation</div>
        </div>
        <div class="confirm-msg" id="confirmMsg">
             Please provide a reason for cancelling this appointment.
        </div>
        <div id="reasonInputWrapper">
            <textarea id="cancelReasonInput" rows="4" placeholder="Type reason here..."></textarea>
        </div>
        <div class="confirm-actions">
            <button id="reasonBack" class="btn-small btn-close">Back</button>
            <button id="reasonSubmit" class="btn-small btn-cancel">Submit Cancellation</button>
        </div>
    </div>
</div>

<footer>
    © 2025 EyeMaster. All rights reserved.
</footer>

<script>
// ===================================
// === LOADER FUNCTIONS =======
// ===================================
const loaderOverlay = document.getElementById('loader-overlay');
const loaderText = document.getElementById('loader-text');

function showLoader(message = 'Loading...') {
    loaderText.textContent = message;
    loaderOverlay.style.display = 'flex';
}

function hideLoader() {
    loaderOverlay.style.display = 'none';
}

document.addEventListener('DOMContentLoaded', () => {
    // Hide default page loader if it exists
    const pageLoader = document.getElementById('page-loader-overlay');
    const content = document.querySelector('.dashboard'); 
    if (pageLoader) pageLoader.style.display = 'none';
    if (content) {
        content.style.visibility = 'visible';
        content.style.display = 'block';
    }
});

// ===================================
// CHART DATA
// ===================================
const dailyData = <?php echo json_encode($dailyData); ?>;
const statusData = <?php echo json_encode($statusData); ?>;
const weeklyData = <?php echo json_encode($weeklyData); ?>;

const dailyLabels = dailyData.length > 0 ? dailyData.map(d => {
    const date = new Date(d.date);
    return (date.getMonth() + 1) + '/' + date.getDate();
}) : ['No Data'];
const dailyValues = dailyData.length > 0 ? dailyData.map(d => parseInt(d.count)) : [0];

const statusLabels = statusData.length > 0 ? statusData.map(s => s.status_name) : ['No Data'];
const statusValues = statusData.length > 0 ? statusData.map(s => parseInt(s.count)) : [1];
const statusColors = statusData.length > 0 ? statusData.map(s => {
    const status = s.status_name.toLowerCase(); 
    if (status.includes('completed') || status.includes('approved')) return '#27ae60'; // Standard Green
    if (status.includes('pending')) return '#f39c12'; // Orange
    if (status.includes('confirmed')) return '#8bc34a'; // <--- NEW COLOR (Light Green/Lime)
    if (status.includes('cancel') || status.includes('missed')) return '#e74c3c'; // Red
    return '#95a5a6';
}) : ['#e0e0e0'];

const dayMap = {
    'Monday': 'Mon', 'Tuesday': 'Tue', 'Wednesday': 'Wed',
    'Thursday': 'Thu', 'Friday': 'Fri', 'Saturday': 'Sat', 'Sunday': 'Sun'
};

const fixedDays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
const weeklyMap = {};
weeklyData.forEach(item => {
    weeklyMap[item.day] = parseInt(item.count);
});

const weeklyLabels = fixedDays.map(day => dayMap[day]);
const weeklyValues = fixedDays.map(day => weeklyMap[day] || 0);
const weeklyColors = weeklyValues.map((val, idx) => idx % 2 === 0 ? '#e74c3c' : '#27ae60');

// Line Chart (Appointments Overview)
const ctx1 = document.getElementById('appointmentsChart').getContext('2d');
new Chart(ctx1, {
    type: 'line',
    data: {
        labels: dailyLabels,
        datasets: [{
            label: 'Appointments',
            data: dailyValues,
            borderColor: '#e74c3c',
            backgroundColor: 'rgba(231, 76, 60, 0.1)',
            borderWidth: 2,
            fill: true,
            tension: 0.4,
            pointRadius: 4,
            pointBackgroundColor: '#e74c3c'
        }]
    },
    options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: { legend: { display: false } },
        scales: {
            y: { beginAtZero: true, grid: { color: '#f0f0f0' }, ticks: { font: { size: 11 } } },
            x: { grid: { display: false }, ticks: { font: { size: 11 } } }
        }
    }
});

// Doughnut Chart (Status)
const ctx2 = document.getElementById('statusChart').getContext('2d');
new Chart(ctx2, {
    type: 'doughnut',
    data: {
        labels: statusLabels,
        datasets: [{
            data: statusValues,
            backgroundColor: statusColors,
            borderWidth: 0
        }]
    },
    options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
            legend: {
                position: 'bottom',
                labels: { padding: 15, font: { size: 11 }, usePointStyle: true, pointStyle: 'circle' }
            }
        }
    }
});

// Bar Chart (Weekly Data)
const ctx3 = document.getElementById('weeklyChart').getContext('2d');
new Chart(ctx3, {
    type: 'bar',
    data: {
        labels: weeklyLabels,
        datasets: [{
            label: 'Appointments',
            data: weeklyValues,
            backgroundColor: weeklyColors,
            borderRadius: 6,
            barThickness: 35
        }]
    },
    options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: { legend: { display: false } },
        scales: {
            y: { beginAtZero: true, grid: { color: '#f0f0f0' }, ticks: { font: { size: 10 } } },
            x: { grid: { display: false }, ticks: { font: { size: 10 } } }
        }
    }
});

// ===================================
// GLOBAL HELPERS
// ===================================
const popup = document.getElementById('popup');
const popupHeader = document.getElementById('popup-header');
const popupContent = document.getElementById('popup-content');
const popupOverlay = document.querySelector('.popup-overlay');
const confirmBtn = document.getElementById('confirmActionBtn');
let html5QrCode = null;

function showGlobalToast(msg, type = 'success') {
    let overlay = document.getElementById('toast-overlay-global');
    if (!overlay) {
        overlay = document.createElement('div');
        overlay.id = 'toast-overlay-global';
        overlay.className = 'toast-overlay';
        document.body.appendChild(overlay);
    }
    
    const toast = document.createElement('div');
    toast.className = `toast ${type}`; 
    toast.innerHTML = `
        <div class="toast-icon">${type === 'success' ? '✓' : '✕'}</div>
        <div class="toast-message">${msg}</div>
    `;
    
    overlay.innerHTML = '';
    overlay.appendChild(toast);
    overlay.classList.add('show');
    
    const timer = setTimeout(() => {
        if(overlay) overlay.classList.remove('show');
    }, 2500);
    
    overlay.addEventListener('click', () => {
        clearTimeout(timer);
        if(overlay) overlay.classList.remove('show');
    }, { once: true });
}

function openPopup(header, content, isConfirmation = false, callback = null) {
    popupHeader.innerHTML = `<h3>${header}</h3>`;
    popupContent.innerHTML = content;
    
    if (isConfirmation) {
        confirmBtn.style.display = 'block';
        confirmBtn.onclick = () => {
            if (callback) callback();
            closePopup();
        };
    } else {
        confirmBtn.style.display = 'none';
        confirmBtn.onclick = null;
    }

    popup.classList.add('active');
    popupOverlay.classList.add('active');
}

function closePopup() { 
    popup.classList.remove('active');
    popupOverlay.classList.remove('active');
    const qrModal = document.getElementById('qrScannerModal');
    if (qrModal && qrModal.style.display !== 'none') {
         stopScan();
    }
}

// ===================================
// DROPDOWN / FILTER LOGIC
// ===================================
function toggleDropdown(id) {
    const dropdown = document.getElementById(id);
    const allDropdowns = document.querySelectorAll('.dropdown');
    
    allDropdowns.forEach(d => {
        if (d.id !== id) d.classList.remove('active');
    });
    
    dropdown.classList.toggle('active');
}

function applyFilter(type, value) {
    showLoader('Applying filter...');
    const url = new URL(window.location);
    url.searchParams.set(type, value);
    
    if (type === 'year') {
        url.searchParams.delete('month');
        url.searchParams.delete('week');
        url.searchParams.delete('day');
    } else if (type === 'month') {
        url.searchParams.delete('week');
        url.searchParams.delete('day');
    } else if (type === 'week') {
        url.searchParams.delete('day');
    }
    
    window.location.href = url.toString();
}

document.addEventListener('click', function(e) {
    if (!e.target.closest('.filter-btn') && !e.target.closest('.dropdown')) {
        document.querySelectorAll('.dropdown').forEach(d => d.classList.remove('active'));
    }
});

// ===================================
// QR SCANNING LOGIC
// ===================================

function stopScan() {
    const qrModal = document.getElementById('qrScannerModal');
    if (qrModal) qrModal.style.display = 'none';

    if (html5QrCode) {
        html5QrCode.stop().then(() => {
            console.log("QR Scanner stopped.");
            const qrReader = document.getElementById('qr-reader');
            if(qrReader) qrReader.innerHTML = '';
        }).catch(err => {
            console.warn('QR scanner stop failed:', err);
            const qrReader = document.getElementById('qr-reader');
            if(qrReader) qrReader.innerHTML = '';
        });
    }
}

function processScannedData(qrCodeMessage) {
    console.log('Processing QR:', qrCodeMessage);
    showLoader('Verifying QR Code...');
    
    fetch('verify_qr.php', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ qr_code: qrCodeMessage })
    })
    .then(response => {
        if (!response.ok) throw new Error('HTTP error ' + response.status);
        return response.json();
    })
    .then(data => {
        hideLoader();
        if (data.success && data.data) {
            openAppointmentDetailModal(data); 
        } else {
            showGlobalToast(data.message || 'Appointment not found', 'error');
        }
    })
    .catch(error => {
        hideLoader();
        console.error(error);
        showGlobalToast('Error: ' + error.message, 'error');
    });
}

function startScan() {
    const qrModal = document.getElementById('qrScannerModal');
    if (!qrModal) return;
    
    qrModal.style.display = 'flex'; 
    const qrReaderId = "qr-reader";
    const qrReaderElement = document.getElementById(qrReaderId);
    if (qrReaderElement) qrReaderElement.innerHTML = '';
    
    html5QrCode = new Html5Qrcode(qrReaderId);
    console.log('Starting QR scanner...');

    Html5Qrcode.getCameras().then(cameras => {
        if (cameras && cameras.length) {
            const cameraId = cameras[cameras.length - 1].id;
            html5QrCode.start(
                cameraId,
                { fps: 10, qrbox: { width: 250, height: 250 } }, 
                qrCodeMessage => {
                    // Success
                    if (html5QrCode) {
                        html5QrCode.stop().then(() => {
                            qrModal.style.display = 'none';
                            processScannedData(qrCodeMessage);
                        }).catch(() => {
                            qrModal.style.display = 'none';
                            processScannedData(qrCodeMessage);
                        });
                    } else {
                        qrModal.style.display = 'none';
                        processScannedData(qrCodeMessage);
                    }
                },
                errorMessage => { /* Ignore minor frame errors */ }
            ).catch(err => {
                stopScan(); 
                showGlobalToast('Unable to start camera: ' + err, 'error');
            });
        } else {
            showGlobalToast('No cameras found on this device.', 'error');
        }
    }).catch(err => {
        showGlobalToast('Camera access denied. Please check permissions.', 'error');
    });
}

// ===================================
// APPOINTMENT DETAIL / ACTIONS
// ===================================
function openAppointmentDetailModal(payload) {
    const d = payload.data; 
    const preformatted = payload; 

    document.getElementById('modal_appointment_id').value = d.appointment_id; 
    document.getElementById('detail-title').textContent = d.service_name || 'Appointment Details';
    document.getElementById('detail-id').textContent = '#' + d.appointment_id;
    
    const modalBody = document.getElementById('detailModalBody');
    modalBody.innerHTML = ''; 

    const labels = {
        'full_name': 'Patient Name', 'status_name': 'Status', 'service_name': 'Service',
        'staff_name': 'Staff Assigned', 'appointment_date': 'Date', 'appointment_time': 'Time',
        'age': 'Age', 'gender': 'Gender', 'phone_number': 'Phone Number',
        'occupation': 'Occupation', 'suffix': 'Suffix', 'symptoms': 'Symptoms',
        'concern': 'Concern', 'wear_glasses': 'Wears Glasses', 'notes': 'Notes',
        'certificate_purpose': 'Certificate Purpose', 'certificate_other': 'Other Certificate',
        'ishihara_test_type': 'Ishihara Test Type', 'ishihara_purpose': 'Ishihara Purpose',
        'color_issues': 'Color Issues', 'previous_color_issues': 'Previous Color Issues',
        'ishihara_notes': 'Ishihara Notes', 'ishihara_reason': 'Ishihara Reason',
        'consent_info': 'Consent (Info)', 'consent_reminders': 'Consent (Reminders)', 'consent_terms': 'Consent (Terms)',
    };
    
    const displayOrder = [
        'full_name', 'status_name', 'service_name', 'staff_name',
        'appointment_date', 'appointment_time', 'age', 'gender', 'phone_number',
        'occupation', 'suffix', 'symptoms', 'concern', 'wear_glasses', 'notes',
        'certificate_purpose', 'certificate_other', 'ishihara_test_type',
        'ishihara_purpose', 'color_issues', 'previous_color_issues', 'ishihara_notes', 'ishihara_reason',
        'consent_info', 'consent_reminders', 'consent_terms'
    ];
    
    let contentHtml = '<div class="detail-grid">';
    
    for (const key of displayOrder) {
        if (d.hasOwnProperty(key) && d[key] !== null && d[key] !== '' && d[key] !== '0') {
            let value = d[key];
            const label = labels[key] || key;
            let rowClass = 'detail-row';
            
            if (['notes', 'symptoms', 'concern', 'ishihara_notes'].includes(key)) {
                rowClass += ' full-width';
            }
            
            if (key === 'appointment_date') value = preformatted.date;
            else if (key === 'appointment_time') value = preformatted.time;
            else if (key.includes('consent')) value = value == 1 ? 'Yes' : 'No';
            else if (key === 'status_name') value = `<span class="badge ${value.toLowerCase()}">${value}</span>`;
            else value = `<b>${value}</b>`;
            
            contentHtml += `
                <div class="${rowClass}">
                    <span class="detail-label">${label}</span>
                    <div class="detail-value">${value}</div>
                </div>
            `;
        }
    }
    contentHtml += '</div>';
    modalBody.innerHTML = contentHtml;
    
    document.getElementById('appointmentDetailModal').classList.add('show');
}

function closeAppointmentDetailModal() {
    document.getElementById('appointmentDetailModal').classList.remove('show');
}

function updateScannedStatus(newStatus, reason = null) {
    const appointmentId = document.getElementById('modal_appointment_id').value;
    
    if (!appointmentId) {
        showGlobalToast('Error: No Appointment ID found.', 'error');
        return;
    }

    showLoader(`Update Status to ${newStatus}...`);

    const bodyParams = {
        action: 'updateStatus',
        id: appointmentId,
        status_name: newStatus 
    };

    if (newStatus === 'Cancel') { 
        bodyParams.reason = reason || 'Cancelled by Admin via QR Scan.';
    }

    fetch('appointment.php', {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: new URLSearchParams(bodyParams)
    })
    .then(res => res.json())
    .then(data => {
        hideLoader();
        if (data.success) {
            closeAppointmentDetailModal();
            showGlobalToast(`Appointment marked as ${newStatus}. Refreshing...`, 'success');
            setTimeout(() => { location.reload(); }, 2000);
        } else {
            showGlobalToast(data.message || 'Failed to update status.', 'error');
        }
    })
    .catch(err => {
        hideLoader();
        console.error('Update Error:', err);
        showGlobalToast('Network error.', 'error');
    });
}

function promptScannedCancel() {
    const modal = document.getElementById('reasonModal');
    const reasonInput = document.getElementById('cancelReasonInput');
    const submitBtn = document.getElementById('reasonSubmit');
    const backBtn = document.getElementById('reasonBack');

    reasonInput.value = ''; 
    modal.classList.add('show');
    modal.setAttribute('aria-hidden', 'false');

    let onKey; 
    function cleanUp() {
        modal.classList.remove('show');
        modal.setAttribute('aria-hidden', 'true');
        document.removeEventListener('keydown', onKey);
    }

    submitBtn.onclick = () => {
        const reason = reasonInput.value.trim();
        if (reason === '') {
            showGlobalToast('A reason is required to cancel.', 'error');
            return;
        }
        cleanUp();
        updateScannedStatus('Cancel', reason); 
    };

    backBtn.onclick = () => cleanUp();
    
    onKey = (e) => { 
        if (e.key === 'Escape') {
            cleanUp();
        }
    };
    document.addEventListener('keydown', onKey);
}

// ===================================
// KEYBOARD SCANNER LISTENER
// ===================================
(function() {
    let qrCodeChars = [];
    let lastKeystrokeTime = new Date();

    document.addEventListener('keydown', function(e) {
        const activeEl = document.activeElement;
        // Don't scan if user is typing in a field
        if (activeEl && (activeEl.tagName === 'INPUT' || activeEl.tagName === 'TEXTAREA')) {
            return; 
        }
        
        const now = new Date();
        if (now - lastKeystrokeTime > 100) {
            qrCodeChars = []; 
        }
        lastKeystrokeTime = now;

        if (e.key === 'Enter' || e.keyCode === 13) {
            if (qrCodeChars.length > 0) { 
                e.preventDefault(); 
                const qrString = qrCodeChars.join('');
                console.log('Handheld Scanner Data:', qrString);
                processScannedData(qrString); 
            }
            qrCodeChars = []; 
        } else {
            if (e.key && e.key.length === 1) {
                qrCodeChars.push(e.key);
            }
        }
    });
})();

// Navigation Toggle
document.addEventListener('DOMContentLoaded', function() {
  const menuToggle = document.getElementById('menu-toggle');
  const mainNav = document.getElementById('main-nav');
  if (menuToggle && mainNav) {
    menuToggle.addEventListener('click', function() {
      mainNav.classList.toggle('show');
      if (mainNav.classList.contains('show')) {
        this.innerHTML = '✕'; 
      } else {
        this.innerHTML = '☰';
      }
    });
  }
});
</script>
</body>
</html>