<?php
// Location: EYE MASTER/admin/admin_dashboard_export.php

// 1. Session Check
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// 2. Enable Error Reporting (For Debugging)
error_reporting(E_ALL);
ini_set('display_errors', 1);

// =======================================================================
// [FIX] PREVENT DOUBLE SESSION START IN INCLUDED FILE
// =======================================================================
define('SKIP_SESSION_START', true);

// 3. Load Dashboard Logic (This provides $statFilter)
ob_start(); 
require_once __DIR__ . '/admin_dashboard-action.php';

// =======================================================================
// [FIX] SMART FILE LOCATOR FOR ENCRYPTION
// =======================================================================
$possible_paths = [
    __DIR__ . '/../../config/encryption_util.php',
    __DIR__ . '/../config/encryption_util.php', 
    $_SERVER['DOCUMENT_ROOT'] . '/config/encryption_util.php',
    $_SERVER['DOCUMENT_ROOT'] . '/capstone/config/encryption_util.php'
];

$encryption_loaded = false;
foreach ($possible_paths as $path) {
    if (file_exists($path)) {
        require_once $path;
        $encryption_loaded = true;
        break; 
    }
}
ob_end_clean(); 
// =======================================================================

// 4. Fetch Data (Full Query WITH FALLBACK JOINS)
// Added JOINs to clients/users to get user_full_name if appointment name is empty
$sql_full_list = "SELECT a.appointment_id, a.full_name, ser.service_name, 
                          a.appointment_date, a.appointment_time, s.status_name,
                          a.phone_number, a.gender, a.age,
                          u.full_name as user_full_name
                  FROM appointments a
                  LEFT JOIN services ser ON a.service_id = ser.service_id
                  LEFT JOIN appointmentstatus s ON a.status_id = s.status_id
                  LEFT JOIN clients c ON a.client_id = c.client_id
                  LEFT JOIN users u ON c.user_id = u.id
                  WHERE {$statFilter} 
                  ORDER BY a.appointment_date ASC, a.appointment_time ASC";

$result_full = $conn->query($sql_full_list);

// 5. Headers for Excel
$filename = "EyeMaster_Dashboard_Report_" . date('Y-m-d_His') . ".xls";
header("Content-Type: application/vnd.ms-excel");
header("Content-Disposition: attachment; filename=\"$filename\"");
header("Pragma: no-cache"); 
header("Expires: 0");
?>

<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
        body { font-family: Arial, sans-serif; font-size: 11pt; }
        table { border-collapse: collapse; width: 100%; margin-bottom: 20px; }
        td, th { border: 1px solid #000000; padding: 6px; vertical-align: middle; }
        
        .main-title { 
            font-size: 16pt; 
            font-weight: bold; 
            background-color: #FFFFFF; 
            color: #000000; 
            border: 2px solid #2ea65a; 
            text-align: left;
        }
        
        .section-header { 
            background-color: #444; 
            color: #FFF;
            font-weight: bold; 
            text-align: left; 
        }

        .table-header { 
            background-color: #e2efda; 
            font-weight: bold; 
            text-align: center; 
        }

        .text-center { text-align: center; }
        .text-bold { font-weight: bold; }

        /* Status Colors */
        .status-completed { color: #16a34a; font-weight: bold; }
        .status-pending { color: #d35400; font-weight: bold; }
        .status-confirmed { color: #27ae60; font-weight: bold; }
        .status-cancelled { color: #c0392b; font-weight: bold; }
    </style>
</head>
<body>

<table>
    <col style="width: 150pt;"> <col style="width: 300pt;">
    <tr>
        <td colspan="9" class="main-title">EYE MASTER CLINIC - MANAGEMENT DASHBOARD REPORT</td>
    </tr>
    <tr>
        <td colspan="2" class="text-bold">Generated By:</td>
        <td colspan="7"><?php echo htmlspecialchars($_SESSION['full_name'] ?? 'Admin'); ?></td>
    </tr>
    <tr>
        <td colspan="2" class="text-bold">Date Generated:</td>
        <td colspan="7"><?php echo date('F j, Y, g:i a'); ?></td>
    </tr>
    <tr>
        <td colspan="2" class="text-bold">Filter Applied:</td>
        <td colspan="7">Year: <?= $filterYear ?> | Month: <?= $filterMonth ?> | Week: <?= $filterWeek ?> | Day: <?= $filterDay ?></td>
    </tr>
</table>

<table>
    <tr><td colspan="9" class="section-header">--- EXECUTIVE SUMMARY STATISTICS ---</td></tr>
    <tr class="table-header">
        <td colspan="2">Metric</td>
        <td>Count</td>
        <td colspan="6">Description</td>
    </tr>
    <tr>
        <td colspan="2">Total Appointments</td>
        <td class="text-center text-bold" style="font-size:12pt;"><?= $totalAppointmentsToday ?></td>
        <td colspan="6">Total appointments within the selected date range</td>
    </tr>
    <tr>
        <td colspan="2">Confirmed</td>
        <td class="text-center status-confirmed"><?= $confirmedAppointments ?></td>
        <td colspan="6">Appointments confirmed</td>
    </tr>
    <tr>
        <td colspan="2">Pending</td>
        <td class="text-center status-pending"><?= $pendingAppointments ?></td>
        <td colspan="6">Appointments awaiting action</td>
    </tr>
    <tr>
        <td colspan="2">Completed</td>
        <td class="text-center status-completed"><?= $completedToday ?></td>
        <td colspan="6">Appointments successfully finished</td>
    </tr>
</table>

<table>
    <tr><td colspan="9" class="section-header">--- STATUS DISTRIBUTION BREAKDOWN ---</td></tr>
    <tr class="table-header">
        <td colspan="3">Status Name</td>
        <td colspan="2">Count</td>
        <td colspan="4">Percentage (Est)</td>
    </tr>
    <?php foreach ($statusData as $row): 
        $percent = ($totalAppointmentsToday > 0) ? round(($row['count'] / $totalAppointmentsToday) * 100, 1) : 0;
    ?>
    <tr>
        <td colspan="3"><?= htmlspecialchars($row['status_name']) ?></td>
        <td colspan="2" class="text-center text-bold"><?= $row['count'] ?></td>
        <td colspan="4"><?= $percent ?>%</td>
    </tr>
    <?php endforeach; ?>
</table>

<table>
    <tr><td colspan="9" class="section-header">--- DETAILED APPOINTMENT LOG ---</td></tr>
    <tr class="table-header">
        <td style="width: 50pt;">ID</td>
        <td style="width: 180pt;">Patient Name</td>
        <td style="width: 180pt;">Service</td>
        <td style="width: 80pt;">Date</td>
        <td style="width: 80pt;">Time</td>
        <td style="width: 100pt;">Status</td>
        <td style="width: 100pt;">Phone</td>
        <td style="width: 60pt;">Gender</td>
        <td style="width: 40pt;">Age</td>
    </tr>

    <?php 
    if ($result_full && $result_full->num_rows > 0):
        while ($row = $result_full->fetch_assoc()):
            
            // --- LOGIC: SELECT NAME SOURCE ---
            if (empty($row['full_name'])) {
                $raw_name = !empty($row['user_full_name']) ? $row['user_full_name'] : '';
            } else {
                $raw_name = $row['full_name'];
            }

            // Defaults
            $d_name   = $raw_name; // Default if encryption fails
            $d_phone  = $row['phone_number'];
            $d_gender = $row['gender'];
            $d_age    = $row['age'];

            if ($encryption_loaded && function_exists('decrypt_data')) {
                // Attempt Decryption
                $try_name   = decrypt_data($raw_name);
                $try_phone  = decrypt_data($row['phone_number']);
                $try_gender = decrypt_data($row['gender']);
                $try_age    = decrypt_data($row['age']);

                // If decryption returns valid string, use it
                if (!empty($try_name))   $d_name   = $try_name;
                if (!empty($try_phone))  $d_phone  = $try_phone;
                if (!empty($try_gender)) $d_gender = $try_gender;
                if (!empty($try_age))    $d_age    = $try_age;
            } else {
                if(!$encryption_loaded) $d_name = "[CONFIG ERROR] " . $d_name;
            }
            
            // Name Fallback Final Check (Visual)
            if (empty($d_name) || $d_name == 'N/A') {
                $d_name = "Walk-in / Unknown";
            }
            // ----------------------------------------------

            $dateDisplay = $row['appointment_date'];
            $timeDisplay = date('g:i A', strtotime($row['appointment_time']));
            $statusClass = 'status-' . strtolower($row['status_name']);
    ?>
    <tr>
        <td class="text-center"><?= $row['appointment_id'] ?></td>
        
        <td><?= htmlspecialchars($d_name) ?></td>
        
        <td><?= htmlspecialchars($row['service_name']) ?></td>
        <td class="text-center" style="mso-number-format:'\@';"><?= $dateDisplay ?></td> 
        <td class="text-center"><?= $timeDisplay ?></td>
        <td class="<?= $statusClass ?>"><?= htmlspecialchars($row['status_name']) ?></td>
        
        <td style="mso-number-format:'\@';"><?= htmlspecialchars($d_phone) ?></td> 
        
        <td class="text-center"><?= htmlspecialchars($d_gender) ?></td>
        <td class="text-center"><?= htmlspecialchars($d_age) ?></td>
    </tr>
    <?php 
        endwhile; 
    else: 
    ?>
    <tr>
        <td colspan="9" class="text-center" style="padding: 20px;">No appointments found.</td>
    </tr>
    <?php endif; ?>

</table>
</body>
</html>
<?php exit(); ?>